### ISSUE TITLE
Error: Multiple commands produce relate to PrivacyInfo.xcprivacy

### ISSUE THREAD

**Issue by duytohoang** [Tealium/tealium-react-native#166]
Hello everyone,

I am developing on a React Native project, but I got an error relate to this library. Could you help me on it?

The error is:

> Error: Multiple commands produce '/Users/mac-00005/Library/Developer/Xcode/DerivedData/MyApp-dtghpfjnagfciefhxuvaqskgwawc/Build/Products/Debug-iphonesimulator/MyApp.app/PrivacyInfo.xcprivacy'

My React Native project information below:

- React Native version 0.73.4
- Tealium-react-native version 2.3.2
- Xcode 15.1

The error occur when I apply the Apple privacy manifest file (**PrivacyInfo.xcprivacy**) into the Xcode project. I added this privacy file to the app's target membership. Note that, this error only occur after I upgraded the Tealium-react-native library to 2.3.2. I am not get this error with version 2.1.3.

I think, maybe I have missing configurations. So, please advise me! Thank you very much!

**Comment by Enricoza** [comment]
Hi @duytohoang, thank you for opening this. 
We will take a look at this and probably make a new release of the underlying tealium-swift SDK to resolve this possible conflict.

**Comment by Enricoza** [comment]
Hi @duytohoang, we just released version [2.12.2](https://github.com/Tealium/tealium-swift/releases/tag/2.12.2) of the tealium-swift SDK. 
This is the library holding the PrivaciInfo manifest, so updating to this version should fix the issue without changing the react native library. 
In order to update you might need to run `pod update tealium-swift` or similar commands to update the internal dependencies of tealium-react-native. 
Make sure the right version is installed, by looking for the `2.12.2` version in the logs or the generated `Podfile.lock`, before trying to build again.

I'm going to close this for now as this solved the issue for me, but please let me know if you have any other issues.
