### ISSUE TITLE
iOS: RCTBridgeModule.h not found

### ISSUE THREAD

**Issue by tothvoj-gl** [Tealium/tealium-react-native#22]
SDK version: 1.0.4
RN version: 0.59.2

After successful  installation, the iOS version can not be built with the following build error: RCTBridgeModule.h not found. Setting the header search path to "$(SRCROOT)/../../../ios/Pods/Headers/Public/React" and "$(SRCROOT)/../../../ios/Pods/Headers/Public/" fixes the issue.

**Comment by jameskeith** [comment]
hi @tothvoj-gl 
I've built out a sample app from scratch using `react-native init <app name>` and then installed and linked the tealium-react-native module. The only manual step that I've had to take is to add the TealiumIOS.framework and TealiumIOSLifecycle.framework files as described in the documentation in order to have my test app build correctly in XCode. [manual steps here](https://docs.tealium.com/platforms/react-native/install/#ios)

Looking at the error message, however, this seems to be something more common with React Native in general. Have you recently updated your React Native versions at all?

**Comment by tothvoj-gl** [comment]
Yes, we are constantly upgrading all our libraries. I can confirm that we have this issue with other libraries as well, so might be something in RN side. I am not an iOS developer so can not provide more insights. Jut wanted to let you know what issue we have been facing during implementation.

**Comment by lutakyn** [comment]
Hi,@tothvoj-gl,i linked tealium manually and got this error,'React/RCTBridgeModule.h' file not found,this is becoming stressful.

**Comment by jameskeith** [comment]
@tothvoj-gl @lutakyn 
I've not been able to reproduce this using the latest release - 1.0.7 - that should support autolinking for you. For reference, I've been testing on React Native v0.61.2 
Can you retest with the new release and let me know if this issues still persists?
